capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from similarmusic import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/', views.data_view),
    path('music/', views.play_music),
    path("", include("similarmusic.urls")),
    path('test/', views.test),
]

similarmusic/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = "similarmusic"

urlpatterns = [
    path("", views.uploadFile, name = "uploadFile"),
    path('data/', views.data_view, name="showing data"),
    path('music/', views.play_music, name = "playing music"),
    path('test/', views.test, name = "view test"),
]

if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )


#바깥에 있는 urls.py랑 뭐가다르지??

similarmusic/models.py
from pyexpat import model
from django.db import models

# Create your models here.

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


class Dataset(models.Model):
    music_id = models.AutoField(primary_key=True)
    musicname = models.CharField(max_length=200)
    length = models.IntegerField(blank=True, null=True)
    rms_mean = models.FloatField(blank=True, null=True)
    rms_var = models.FloatField(blank=True, null=True)
    bpm = models.FloatField(blank=True, null=True)
    zero_crossing_rate_mean = models.FloatField(blank=True, null=True)
    zero_crossing_rate_var = models.FloatField(blank=True, null=True)
    harmony_mean = models.FloatField(blank=True, null=True)
    harmony_var = models.FloatField(blank=True, null=True)
    percussive_mean = models.FloatField(blank=True, null=True)
    percussive_var = models.FloatField(blank=True, null=True)
    spectral_centroid_mean = models.FloatField(blank=True, null=True)
    spectral_centroid_var = models.FloatField(blank=True, null=True)
    spectral_bandwidth_mean = models.FloatField(blank=True, null=True)
    spectral_bandwidth_var = models.FloatField(blank=True, null=True)
    spectral_rolloff_mean = models.FloatField(blank=True, null=True)
    spectral_rolloff_var = models.FloatField(blank=True, null=True)
    chroma_frequencies_mean = models.FloatField(blank=True, null=True)
    chroma_frequencies_var = models.FloatField(blank=True, null=True)
    mfcc1_mean = models.FloatField(blank=True, null=True)
    mfcc1_var = models.FloatField(blank=True, null=True)
    mfcc2_mean = models.FloatField(blank=True, null=True)
    mfcc2_var = models.FloatField(blank=True, null=True)
    mfcc3_mean = models.FloatField(blank=True, null=True)
    mfcc3_var = models.FloatField(blank=True, null=True)
    mfcc4_mean = models.FloatField(blank=True, null=True)
    mfcc4_var = models.FloatField(blank=True, null=True)
    mfcc5_mean = models.FloatField(blank=True, null=True)
    mfcc5_var = models.FloatField(blank=True, null=True)
    mfcc6_mean = models.FloatField(blank=True, null=True)
    mfcc6_var = models.FloatField(blank=True, null=True)
    mfcc7_mean = models.FloatField(blank=True, null=True)
    mfcc7_var = models.FloatField(blank=True, null=True)
    mfcc8_mean = models.FloatField(blank=True, null=True)
    mfcc8_var = models.FloatField(blank=True, null=True)
    mfcc9_mean = models.FloatField(blank=True, null=True)
    mfcc9_var = models.FloatField(blank=True, null=True)
    mfcc10_mean = models.FloatField(blank=True, null=True)
    mfcc10_var = models.FloatField(blank=True, null=True)
    mfcc11_mean = models.FloatField(blank=True, null=True)
    mfcc11_var = models.FloatField(blank=True, null=True)
    mfcc12_mean = models.FloatField(blank=True, null=True)
    mfcc12_var = models.FloatField(blank=True, null=True)
    mfcc13_mean = models.FloatField(blank=True, null=True)
    mfcc13_var = models.FloatField(blank=True, null=True)
    mfcc14_mean = models.FloatField(blank=True, null=True)
    mfcc14_var = models.FloatField(blank=True, null=True)
    mfcc15_mean = models.FloatField(blank=True, null=True)
    mfcc15_var = models.FloatField(blank=True, null=True)
    mfcc16_mean = models.FloatField(blank=True, null=True)
    mfcc16_var = models.FloatField(blank=True, null=True)
    mfcc17_mean = models.FloatField(blank=True, null=True)
    mfcc17_var = models.FloatField(blank=True, null=True)
    mfcc18_mean = models.FloatField(blank=True, null=True)
    mfcc18_var = models.FloatField(blank=True, null=True)
    mfcc19_mean = models.FloatField(blank=True, null=True)
    mfcc19_var = models.FloatField(blank=True, null=True)
    mfcc20_mean = models.FloatField(blank=True, null=True)
    mfcc20_var = models.FloatField(blank=True, null=True)
    # audio_file = models.FileField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dataset'


class Document(models.Model):
    title = models.CharField(max_length = 500, null = True,blank = True)
    uploadedFile = models.FileField(upload_to = "Uploaded Files/")
    dateTimeOfUpload = models.DateTimeField(auto_now = True)



class Music(models.Model):
    music_title = models.CharField(max_length = 300)
    audio_file = models.FileField()

similarmusic/views.py
import csv
import numpy as np
import librosa
import pandas as pd
import sklearn

from django.shortcuts import render
from django.http import HttpResponse
from . import models

from .models import Dataset, Music #DB 모델 사용 가능하도록 import

import compare_music
import compare_newmusic

# Create your views here.

def data_view(request):
    data = Dataset.objects.all()
    music = Music.objects.all()
    return render(request, 'index.html',{"data":data})


def play_music(request):
    music = Music.objects.all()
    return render(request, 'show-files.html',{"music":music})

def uploadFile(request):
    if request.method == "POST":
        # Fetching the form data
        fileTitle = request.POST.get("fileTitle")
        uploadedFile = request.FILES["uploadedFile"]

        # Saving the information in the database
        document = models.Document(
            title = fileTitle,
            uploadedFile = uploadedFile
            
        )
        document.save()

    documents = models.Document.objects.all()

    return render(request, "similarmusic/upload-file.html", context = {
        "files": documents
    })


def play_music2(request):
    musics = compare_newmusic.compare_music()
    return render(request, 'show-files.html',{"musics":musics})

def test(request):
    name = compare_music.say_hello("재영")
    return render(request,'test.html',{"name":name} )

similarmusic/templates/similarmusic/index.html
<!DOCTYPE html>


<table class = "table-contents" style = "padding: 10px">
    <tr>
        <th>노래 번호</th>
        <th>노래 이름</th>
    </tr>
    {% for Dataset in data %}
    
    <tr>
        <td>{{Dataset.music_id}}</td>
        <td>{{Dataset.musicname}}</td>
    </tr>
    
    {%endfor%}

 
</table>

similarmusic/templates/similarmusic/show-files.html
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<title>결과 데이터 출력</title>
</head>
<body>
	<div style = "text-align:center;">
		<h1>유사도 순위</h1>
	</div>
	<hr>
	<table>
		<tbody>
		<tr><td>1.</td></tr>
		<tr><td>2.</td></tr>
		<tr><td>3.</td></tr>
		<tr><td>4.</td></tr>
		<tr><td>5.</td></tr>
		</tbody>
	</table>

</body>
</html>


<!-- <!DOCTYPE html>

{% for music in music %}
<h1>{{music.title}}</h1>
<audio controls><source src="{{music.audio_file.url}}" type="audio/wav"></audio>

{%endfor%}
 -->

similarmusic/templates/similarmusic/test.html
<!DOCTYPE html>

<h1>테스트용 화면</h1>

<h2>{{name}}</h2>

similarmusic/templates/similarmusic/upload-file.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django File Upload</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');

        * {
            font-family: "Roboto";
        }

        body {
            background-color: #F5F5F5;
        }

        form {
            background-color: #FFFFFF;
            padding: 25px;
        }

        table {
            width: 100%; 
            text-align: center;
            margin-top: 25px;
            padding: 25px;
            background-color: #FFFFFF;
        }

        table tr td {
            padding-top: 15px;            
        }
    </style>
</head>
<body>
    <h2>음악 파일 업로드</h2>
    <form action="{% url 'similarmusic:uploadFile' %}" method="POST" enctype="multipart/form-data">
        <input type="file" name="uploadedFile">
        {% csrf_token %}
        <input type="submit" value="Upload">
    </form>
    <table>
        <caption><h2>업로드 확인</h2></caption>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>File Path</th>
            <th>Upload Date & Time</th>
        </tr>
        {% for file in files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.title }}</td>
                <td>{{ file.uploadedFile.url }}</td>
                <td>{{ file.dateTimeOfUpload }}</td>
            </tr>
        {% endfor %}
    </table>
    <button type = "button" onclick="location.href='/music'">분석 결과 보기</button>
    <button type = "button" onclick="location.href='/data'">모든 음악 보기</button>
    <!-- 분석결과 보기 버튼을 누르면 /music으로 연결되는데, 현재 music 페이지는 
    오디오 플레이어 테스트 용이고, 여기에(music페이지에) 추가적으로 compare 결과물과 해당 음원 파일의 오디오 플레이어가
    재생되는 페이지를 넣을 것입니다. -->
</body>
</html>